org.gradle.java.home=C:/Program Files/Zulu/zulu-21
org.gradle.jvmargs=-Xmx2G -Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2,TLSv1.3 
org.gradle.parallel=true

# Platform Properties
minecraft_version=1.21.1
neoforge_version=21.1.240
loader_version=0.17.2

# Mod Properties
maven_group=com.shiroha233.mmdskin

# Dependencies
architectury_version=13.0.8
cloth_config_version=15.0.140
fabric_version=0.100.0+1.21.1

# 运行游戏时的人物名称
minecraft_username=Developer

