architectury {
	common("fabric", "neoforge")
}

def nativeResourcesDir = rootProject.layout.buildDirectory.dir("generated/native-resources")

sourceSets {
	main {
		resources {
			srcDir(nativeResourcesDir)
		}
	}
}

dependencies {
	modImplementation "dev.architectury:architectury:${rootProject.architectury_version}"
	compileOnly "net.fabricmc:fabric-loader:${rootProject.loader_version}"

	// MP3 解码依赖
	compileOnly("javazoom:jlayer:1.0.1") { transitive = false }

	testImplementation "org.junit.jupiter:junit-jupiter-api:5.10.2"
	testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.10.2"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

tasks.named("processResources").configure {
	dependsOn rootProject.tasks.named("prepareNativeResources")
}

tasks.named("sourcesJar").configure {
	dependsOn rootProject.tasks.named("prepareNativeResources")
}

test {
	useJUnitPlatform()
}
